services:
  typesense:
    image: typesense/typesense:26.0
    container_name: typesense
    restart: unless-stopped
    environment:
      TYPESENSE_API_KEY: ${TYPESENSE_API_KEY}
      TYPESENSE_DATA_DIR: /data
    ports:
      - "8108:8108"
    volumes:
      - ./data/phase_2/typesense_data:/data
    command: >
      --data-dir /data
      --api-key=${TYPESENSE_API_KEY}
      --listen-port 8108
      --enable-cors
