services:
  typesense:
    image: typesense/typesense:26.0
    container_name: typesense
    restart: unless-stopped
    environment:
      TYPESENSE_API_KEY: ${TYPESENSE_API_KEY}
      TYPESENSE_DATA_DIR: /data
    ports:
      - "8108:8108"
    volumes:
      - ./data/phase_2/typesense_data:/data
    command: >
      --data-dir /data
      --api-key=${TYPESENSE_API_KEY}
      --listen-port 8108
      --enable-cors


  qdrant:
    image: qdrant/qdrant:v1.11.5
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./data/phase_3/qdrant_storage:/qdrant/storage

  postgres:
    image: postgres:16
    container_name: search_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${PGDATABASE:-searchlogs}
      POSTGRES_USER: ${PGUSER:-searchuser}
      POSTGRES_PASSWORD: ${PGPASSWORD:-searchpass}
    ports:
      - "5432:5432"
    volumes:
      - ./data/phase_4/postgres:/var/lib/postgresql/data
